#!/usr/bin/env python
"""etable_sleep_device_jno.py -- eTable 6: Fitbit sleep by decile of the distance, separately for
program-provided devices and participants' own devices, adjusted for age and sex within each device source.

LOCAL. Reads the downloaded sleep_device_deciles/sleep_device_deciles.csv (workbench/sleep_device_deciles.py).
OUTPUTS  ../outputs/tables/etable_sleep_device_jno.{tex,csv}

Run:  python etable_sleep_device_jno.py
"""
import os

import pandas as pd

from etable_deciles_jno import ENCODERS, cell, fmt

HERE = os.path.dirname(os.path.abspath(__file__))
WB = os.path.join(HERE, "..", "outputs", "workbench", "R2025Q4R6")
OUT = os.path.join(HERE, "..", "outputs", "tables")
D = list(range(1, 11))
SOURCES = [("program", "Program-provided device"), ("own", "Own device")]
ROWS = [("sleep_mean_adj", "sleep_mean_adj_lo", "sleep_mean_adj_hi", "Mean sleep per night, min"),
        ("sleep_var_median_adj", "sleep_var_median_adj_lo", "sleep_var_median_adj_hi", "Night-to-night variation, min")]


def main():
    S = pd.read_csv(os.path.join(WB, "sleep_device_deciles", "sleep_device_deciles.csv"))
    lines, out = [], []
    for enc, enc_label in ENCODERS:
        ci = enc == ENCODERS[0][0]
        lines.append(f"\\midrule\\multicolumn{{12}}{{@{{}}l}}{{\\textbf{{{enc_label}}}}} \\\\")
        for src, src_label in SOURCES:
            c0 = S[(S.source == src) & (S.grouping == "cohort")].iloc[0]
            g = S[(S.source == src) & (S.grouping == enc)].set_index("decile")
            lines.append(f"\\multicolumn{{12}}{{@{{}}l}}{{\\textit{{{src_label}}}}} \\\\")
            if ci:
                lines.append(f"\\hspace*{{1em}}Participants, No. & {int(c0.n_sleep)} & "
                             + " & ".join(str(int(g.at[j, 'n_sleep'])) for j in D) + " \\\\")
            for v, lo, hi, lab in ROWS:
                coh = fmt(c0[v.replace("_adj", "")], 1)
                lines.append(f"\\hspace*{{1em}}{lab} & {coh} & "
                             + " & ".join(cell(g.at[j, v], g.at[j, lo], g.at[j, hi], 1, ci) for j in D) + " \\\\")
                out += [{"encoder": enc, "source": src, "measure": v, "decile": j, "value": g.at[j, v], "lo": g.at[j, lo],
                         "hi": g.at[j, hi], "n_sleep": g.at[j, "n_sleep"], "cohort": c0[v.replace("_adj", "")]} for j in D]
    head = "Outcome & Cohort & " + " & ".join(str(j) for j in D) + " \\\\"
    cap = ("\\caption{\\textbf{eTable \\eTabSleepDevice. Sleep by Decile of the Distance, Within Each Device Source.} "
           "Participants with at least 14 nights of Fitbit sleep data, split by whether their device was provided by the "
           "program's wear study (enrolled in the study) or their own (not enrolled). Values are adjusted for age and sex, "
           "and night-to-night variation also for the number of nights, against expected values estimated within each "
           "device source, so each source is compared with its own cohort value (eMethods \\eMethMeasures{}). For the prespecified "
           "encoder, each value is followed by its 95\\% CI. Night-to-night variation is the median of the participants' "
           "SDs of minutes asleep.}\\label{etab:sleepdevice}")
    tex = ["% generated by scripts/etable_sleep_device_jno.py -- do not edit by hand",
           "\\begingroup\\scriptsize\\setlength{\\tabcolsep}{2.5pt}\\renewcommand{\\arraystretch}{1.9}",
           "\\begin{longtable}{@{}>{\\raggedright\\arraybackslash}p{5.0cm}r*{10}{c}@{}}",
           cap + " \\\\", "\\toprule", " & & \\multicolumn{10}{c}{Decile of the distance} \\\\", "\\cmidrule(l){3-12}",
           head, "\\endfirsthead", "\\toprule", head, "\\endhead", "\\bottomrule", "\\endfoot"] + lines + \
          ["\\end{longtable}", "\\endgroup"]
    os.makedirs(OUT, exist_ok=True)   # a fresh copy has no outputs/tables yet
    open(os.path.join(OUT, "etable_sleep_device_jno.tex"), "w").write("\n".join(tex) + "\n")
    pd.DataFrame(out).to_csv(os.path.join(OUT, "etable_sleep_device_jno.csv"), index=False)
    print("wrote", os.path.join(OUT, "etable_sleep_device_jno.tex"))


if __name__ == "__main__":
    main()
