#!/usr/bin/env python
"""etable_groups_jno.py -- eTable 4 of the JAMA Network Open supplement: every semantic group under each of
the 6 encoders, ONE ROW PER GROUP, named by the documented constructs of all its core items.

A group whose core items carry opposite signs stays 1 row: groups are read by size only. The Results count the 27
groups of gte as they are: 13 on 1 construct, 10 on 2, 4 on 3 to 5 (components.csv, n_constructs). This table lists
exactly those groups.

A group's core items are the fixed-point participation-ratio core down its column of the item-by-group matrix
(eMethods 1), so the core has no free threshold. The core items themselves, by item ID, are in Supplement 2
(semantic_group_cores.csv, scripts/supp_items_jno.py), and the item texts beside them.

Reads   outputs/basis/components.csv, data/items_151.csv
Writes  outputs/tables/etable_groups_jno.tex (longtable, caption inside), etable_groups_jno.csv
Run     python scripts/etable_groups_jno.py
"""
import os

import pandas as pd

from construct_labels import display_listed   # display names in the printed table (CSV keeps the data labels)

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(HERE, "outputs", "tables")
ENCODERS = ["gte-large-en-v1.5", "bge-m3", "bge-large-en-v1.5", "all-mpnet-base-v2", "e5-large-v2",
            "qwen3-embedding-0.6b"]
esc = lambda s: (str(s).replace("\\", "").replace("&", "\\&").replace("%", "\\%").replace("$", "\\$")
                 .replace("#", "\\#").replace("_", "\\_"))


def main():
    c = pd.read_csv(os.path.join(HERE, "outputs", "basis", "components.csv"))
    it = pd.read_csv(os.path.join(HERE, "data", "items_151.csv")).set_index("item")
    # the abbreviation in the instrument's display name (eTable 1 spells each out); commas, not semicolons, separate
    # list entries (zero-semicolon rule), and the full names themselves contain commas
    abbr = it["instrument"].str.extract(r"\(([^()]*)\)\s*$")[0]
    inst = abbr.where(it["instrument"] != "single item", "single question")
    assert inst.notna().all(), f"no abbreviation for {sorted(set(it.instrument[inst.isna()]))}"
    rows, head = [], []
    for enc in ENCODERS:
        d = c[c["encoder"] == enc].copy()
        d["instruments"] = [sorted({inst[i] for i in s.split()}) for s in d["core_items"]]
        d["n_instruments"] = d["instruments"].str.len()
        covered = set().union(*[set(s.split()) for s in d["core_items"]])
        head.append({"encoder": enc, "k": len(d), "one": int((d.n_constructs == 1).sum()),
                     "two": int((d.n_constructs == 2).sum()), "more": int((d.n_constructs >= 3).sum()),
                     "multi_instrument": int((d.n_instruments > 1).sum()), "no_core": 151 - len(covered)})
        for r in d.sort_values(["n_core_items", "component"], ascending=[False, True]).itertuples():
            rows.append({"encoder": enc, "group": int(r.component), "n_core_items": int(r.n_core_items),
                         "constructs": r.construct_profile.replace(":", " ").replace("; ", ", "),
                         "instruments": ", ".join(r.instruments)})
    R, H = pd.DataFrame(rows), pd.DataFrame(head)
    os.makedirs(OUT, exist_ok=True)   # a fresh copy has no outputs/tables yet
    R.to_csv(os.path.join(OUT, "etable_groups_jno.csv"), index=False)

    cap = ("\\textbf{eTable \\eTabGroups. The Semantic Groups Under Each of the 6 Encoders.} One row per group. A "
           # "the items with its largest weights", not "most of its weight": the core share of squared weight is a
           # median 0.54 and below half for 11 of 27 gte groups
           "group's core items are the items with its largest weights, the fixed-point participation-ratio core of "
           "its column (eMethods \\eMethGroups{}), so the core does not depend on a chosen threshold. Each group is named by "
           "the documented constructs of all its core items, with the number of core items per construct, largest first. "
           "The groups were formed from the item text alone, before any participant's answers were used, so an item's "
           "group membership does not depend on its instrument. Cores can overlap. An item can be in more than 1 core, "
           "and some items are not in any core. The core items of every group, by item, and the text embedded for each item are in Supplement "
           "\\SuppItemText{}. Instrument abbreviations are spelled out in eTable \\eTabItems{}. gte-large-en-v1.5 is the "
           "prespecified encoder.")
    L = ["% generated by scripts/etable_groups_jno.py -- do not edit by hand",
         "\\begingroup\\footnotesize\\setlength{\\tabcolsep}{4pt}",
         "\\begin{longtable}{@{}r r >{\\raggedright\\arraybackslash}p{0.44\\linewidth} "
         ">{\\raggedright\\arraybackslash}p{0.28\\linewidth}@{}}",   # fits the text width
         f"\\caption{{{cap}}}\\label{{etab:groups}}\\\\",
         "\\toprule Group & Core items & Constructs of the core items & Instruments of the core items \\\\ \\midrule",
         "\\endfirsthead \\toprule Group & Core items & Constructs of the core items & Instruments of the core items "
         "\\\\ \\midrule \\endhead",
         "\\bottomrule \\endfoot"]
    for h in H.itertuples():
        L.append(f"\\multicolumn{{4}}{{@{{}}p{{0.97\\linewidth}}}}{{\\textbf{{{esc(h.encoder)}}} \\quad {h.k} groups, {h.one} on 1 "
                 f"construct, {h.two} on 2, {h.more} on 3 or more, {h.multi_instrument} with core items from more than "
                 f"1 instrument, {h.no_core} items not in any core}} \\\\[2pt]")
        for r in R[R.encoder == h.encoder].itertuples():
            L.append(f"G{r.group + 1} & {r.n_core_items} & {esc(display_listed(r.constructs))} & {esc(r.instruments)} \\\\")
        L.append("\\addlinespace[4pt]")
    L += ["\\end{longtable}", "\\endgroup"]
    open(os.path.join(OUT, "etable_groups_jno.tex"), "w").write("\n".join(L) + "\n")
    print(H.to_string(index=False))
    print(f"{len(R)} groups -> {OUT}/etable_groups_jno.{{tex,csv}}")


if __name__ == "__main__":
    main()
